name: Testing and validation

on:
  workflow_call:
    inputs:
      node:
        description: 'Node version to use'
        default: 16.x
        type: string

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: Set up Node.js ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Run linter
      run: npm run lint

  test:
    name: Tests
    needs: linting
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: Set up Node.js ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Run tests
      run: npm test -- --configuration=ci

  test_build:
    name: Test build
    needs: test
    runs-on: ubuntu-latest
  
    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: Set up Node.js ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Build
      run: npm run build
